set my_verilog_files [ list \
../../src/verilog/rtl/common/build/global_definitions.v \
../../src/verilog/rtl/common/build/issue_definitions.v \
../../src/verilog/rtl/alu/build/alu_definitions.v \
../../src/verilog/rtl/lsu/build/lsu_definitions.v \
../../src/verilog/rtl/decode/build/decode_definitions.v \
../../src/verilog/rtl/common/build/decoder_10_to_1024.v \
../../src/verilog/rtl/common/build/decoder_6_to_40.v \
../../src/verilog/rtl/common/build/decoder_9_to_512.v \
../../src/verilog/rtl/common/build/mux_40x64b_to_1x64b.v \
../../src/verilog/rtl/common/build/mux_40xX_to_1xX.v \
../../src/verilog/rtl/common/build/adder1bit.v \
../../src/verilog/rtl/common/build/adder_param.v \
../../src/verilog/rtl/common/build/circular_barrel_shift.v \
../../src/verilog/rtl/common/build/decoder_6b_40b_en.v \
../../src/verilog/rtl/common/build/decoder_param_en.v \
../../src/verilog/rtl/common/build/decoder_param.v \
../../src/verilog/rtl/common/build/dff_en.v \
../../src/verilog/rtl/common/build/dff_set_en_rst.v \
../../src/verilog/rtl/common/build/dff_set_en.v \
../../src/verilog/rtl/common/build/dff_set.v \
../../src/verilog/rtl/common/build/dff.v \
../../src/verilog/rtl/common/build/encoder_5b_3b.v \
../../src/verilog/rtl/common/build/encoder.v \
../../src/verilog/rtl/common/build/mux2_1.v \
../../src/verilog/rtl/common/build/mux_param.v \
../../src/verilog/rtl/common/build/nand2.v \
../../src/verilog/rtl/common/build/not1.v \
../../src/verilog/rtl/common/build/priority_encoder_40to6.v \
../../src/verilog/rtl/common/build/queue_param_1r_1w.v \
../../src/verilog/rtl/common/build/reg_32b.v \
../../src/verilog/rtl/common/build/reg_40b_set.v \
../../src/verilog/rtl/common/build/reg_40b.v \
../../src/verilog/rtl/common/build/reg_40xX_1r_1w.v \
../../src/verilog/rtl/common/build/reg_40xX_2r_1w.v \
../../src/verilog/rtl/common/build/reg_64b.v \
../../src/verilog/rtl/common/build/regfile.v \
../../src/verilog/rtl/common/build/register.v \
../../src/verilog/rtl/common/build/reg_param.v \
../../src/verilog/rtl/decode/build/decode_core.v \
../../src/verilog/rtl/decode/build/decode.v \
../../src/verilog/rtl/decode/build/flag_generator.v \
../../src/verilog/rtl/decode/build/instr_collate.v \
../../src/verilog/rtl/decode/build/PS_flops_wavepool_decode.v \
../../src/verilog/rtl/decode/build/reg_field_encoder.v \
../../src/verilog/rtl/exec/build/reg_40xX_1r_2w.v \
../../src/verilog/rtl/exec/build/reg_40xX_2r_2w.v \
../../src/verilog/rtl/exec/build/reg_40xX_2r_3w.v \
../../src/verilog/rtl/exec/build/exec.v \
../../src/verilog/rtl/exec/build/rd_port_9_to_1.v \
../../src/verilog/rtl/exec/build/wr_port_40x64b_8_to_1.v \
../../src/verilog/rtl/fetch/build/adder6bit.v \
../../src/verilog/rtl/fetch/build/adder7bit.v \
../../src/verilog/rtl/fetch/build/adder.v \
../../src/verilog/rtl/fetch/build/add_wraparound_after40.v \
../../src/verilog/rtl/fetch/build/decoder.v \
../../src/verilog/rtl/fetch/build/dff_clr.v \
../../src/verilog/rtl/fetch/build/dff_en_fixed_reset_value.v \
../../src/verilog/rtl/fetch/build/fetch_controller.v \
../../src/verilog/rtl/fetch/build/fetch.v \
../../src/verilog/rtl/fetch/build/incr_wraparound_at40.v \
../../src/verilog/rtl/fetch/build/mask_gen.v \
../../src/verilog/rtl/fetch/build/mux4to1_6bit.v \
../../src/verilog/rtl/fetch/build/pc_block.v \
../../src/verilog/rtl/fetch/build/regblock.v \
../../src/verilog/rtl/fetch/build/regfile_clr.v \
../../src/verilog/rtl/fetch/build/round_robin.v \
../../src/verilog/rtl/fetch/build/vacant_mask_gen.v \
../../src/verilog/rtl/fetch/build/wavegrp_info.v \
../../src/verilog/rtl/fetch/build/wfid_generator.v \
../../src/verilog/rtl/issue/build/gpr_dependency_table.v \
../../src/verilog/rtl/issue/build/ready_bits_demux.v \
../../src/verilog/rtl/issue/build/sgpr_busy_table_decoder.v \
../../src/verilog/rtl/issue/build/sgpr_busy_table_mux.v \
../../src/verilog/rtl/issue/build/vgpr_busy_table_decoder.v \
../../src/verilog/rtl/issue/build/vgpr_busy_table_mux.v \
../../src/verilog/rtl/issue/build/alu_issue_logic.v \
../../src/verilog/rtl/issue/build/arbiter.v \
../../src/verilog/rtl/issue/build/barrier_wait.v \
../../src/verilog/rtl/issue/build/branch_wait.v \
../../src/verilog/rtl/issue/build/busy_gpr_table.v \
../../src/verilog/rtl/issue/build/circular_barrel_shift_5b.v \
../../src/verilog/rtl/issue/build/finished_wf.v \
../../src/verilog/rtl/issue/build/functional_unit_reg_bank.v \
../../src/verilog/rtl/issue/build/functional_unit_reg.v \
../../src/verilog/rtl/issue/build/inflight_instr_counter.v \
../../src/verilog/rtl/issue/build/instr_info_table.v \
../../src/verilog/rtl/issue/build/instruction_arbiter.v \
../../src/verilog/rtl/issue/build/issue_flow_control.v \
../../src/verilog/rtl/issue/build/issue_input_flops.v \
../../src/verilog/rtl/issue/build/issue.v \
../../src/verilog/rtl/issue/build/mem_wait.v \
../../src/verilog/rtl/issue/build/mux_40xPARAMb_to_1xPARAMb.v \
../../src/verilog/rtl/issue/build/scoreboard.v \
../../src/verilog/rtl/issue/build/sgpr_comparator.v \
../../src/verilog/rtl/issue/build/spr_dependency_table.v \
../../src/verilog/rtl/issue/build/valid_entry.v \
../../src/verilog/rtl/issue/build/vgpr_comparator.v \
../../src/verilog/rtl/lsu/build/lsu_addr_calculator.v \
../../src/verilog/rtl/lsu/build/lsu.v \
../../src/verilog/rtl/lsu/build/ds_addr_calc.v \
../../src/verilog/rtl/lsu/build/lsu_in_flight_counter.v \
../../src/verilog/rtl/lsu/build/lsu_rd_stage_router.v \
../../src/verilog/rtl/lsu/build/lsu_transit_table.v \
../../src/verilog/rtl/lsu/build/lsu_wb_router.v \
../../src/verilog/rtl/lsu/build/mtbuf_addr_calc.v \
../../src/verilog/rtl/lsu/build/PS_flops_ex_mem_lsu.v \
../../src/verilog/rtl/lsu/build/PS_flops_issue_lsu.v \
../../src/verilog/rtl/lsu/build/PS_flops_mem_wb_lsu.v \
../../src/verilog/rtl/lsu/build/PS_flops_rd_ex_lsu.v \
../../src/verilog/rtl/salu/build/salu.v \
../../src/verilog/rtl/salu/build/salu_controller.v \
../../src/verilog/rtl/salu/build/scalar_alu.v \
../../src/verilog/rtl/sgpr/build/mux_512x32b_to_1x128b.v \
../../src/verilog/rtl/sgpr/build/mux_512x32b_to_1x32b.v \
../../src/verilog/rtl/sgpr/build/mux_512x32b_to_1x64b.v \
../../src/verilog/rtl/sgpr/build/reg_512x32b_6r_3w.v \
../../src/verilog/rtl/sgpr/build/sgpr_simx_rd_port_mux.v \
../../src/verilog/rtl/sgpr/build/sgpr_simx_wr_port_mux.v \
../../src/verilog/rtl/sgpr/build/sgpr.v \
../../src/verilog/rtl/simd/build/amultp2_32x32.v \
../../src/verilog/rtl/simd/build/simd_alu.v \
../../src/verilog/rtl/simd/build/simd_instr_decoder.v \
../../src/verilog/rtl/simd/build/simd.v \
../../src/verilog/rtl/vgpr/build/mux_1024x32b_to_1x128b.v \
../../src/verilog/rtl/vgpr/build/mux_1024x32b_to_1x32b.v \
../../src/verilog/rtl/vgpr/build/reg_1024x32b_5r_2w.v \
../../src/verilog/rtl/vgpr/build/vgpr.v \
../../src/verilog/rtl/vgpr/build/rd_port_mux_8to1.v \
../../src/verilog/rtl/vgpr/build/reg_64bank_1024x32b_5r_2w.v \
../../src/verilog/rtl/vgpr/build/wfid_mux_8to1.v \
../../src/verilog/rtl/vgpr/build/wr_port_mux_8to1.v \
../../src/verilog/rtl/wavepool/build/decoder_3_to_8.v \
../../src/verilog/rtl/wavepool/build/mux_40x35b_to_1x35b.v \
../../src/verilog/rtl/wavepool/build/mux_8x64b_to_1x64b.v \
../../src/verilog/rtl/wavepool/build/wavepool.v \
../../src/verilog/rtl/wavepool/build/adder3bit.v \
../../src/verilog/rtl/wavepool/build/PS_flops_fetch_wavepool.v \
../../src/verilog/rtl/wavepool/build/queue_controller.v \
../../src/verilog/rtl/wavepool/build/reg_35b.v \
../../src/verilog/rtl/wavepool/build/reg_3b.v \
../../src/verilog/rtl/wavepool/build/reg_40x35b_1r_1w.v \
../../src/verilog/rtl/wavepool/build/reg_8x64b_1r_1w.v \
../../src/verilog/rtl/wavepool/build/scbd_feeder.v \
../../src/verilog/rtl/wavepool/build/wavepool_controller.v \
../../src/verilog/rtl/wavepool/build/wave_queue.v \
../../src/verilog/rtl/wavepool/build/wq_pool.v \
../../src/verilog/rtl/compute_unit/build/compute_unit.v \
../../src/verilog/rtl/alu/build/alu_controller.v \
../../src/verilog/rtl/alu/build/alu_fsm.v \
../../src/verilog/rtl/alu/build/alu.v \
../../src/verilog/rtl/alu/build/alu_wb_queue.v \
../../src/verilog/rtl/alu/build/dest_shift_reg.v \
../../src/verilog/rtl/alu/build/mux_2_to_1.v \
../../src/verilog/rtl/alu/build/PS_flops_EX_WB_alu.v \
../../src/verilog/rtl/alu/build/PS_flops_issue_alu.v \
../../src/verilog/rtl/alu/build/shift_in.v \
../../src/verilog/rtl/alu/build/shift_out.v \
../../src/verilog/rtl/alu/build/src_mux.v \
../../src/verilog/rtl/alu/build/src_shift_reg.v \
../../src/verilog/rtl/alu/build/valu.v \
../../src/verilog/rtl/rfa/build/circular_shift.v \
../../src/verilog/rtl/rfa/build/priority_encoder_16_to_4.v \
../../src/verilog/rtl/rfa/build/rfa.v \
../../src/verilog/rtl/simf/build/fpu_addsub.v \
../../src/verilog/rtl/simf/build/fpu_arith.v \
../../src/verilog/rtl/simf/build/fpu_div.v \
../../src/verilog/rtl/simf/build/fpu_intfloat_conv_except.v \
../../src/verilog/rtl/simf/build/fpu_intfloat_conv.v \
../../src/verilog/rtl/simf/build/fpu_mul.v \
../../src/verilog/rtl/simf/build/fpu_post_norm_addsub.v \
../../src/verilog/rtl/simf/build/fpu_post_norm_div.v \
../../src/verilog/rtl/simf/build/fpu_post_norm_intfloat_conv.v \
../../src/verilog/rtl/simf/build/fpu_post_norm_mul.v \
../../src/verilog/rtl/simf/build/fpu_pre_norm_addsub.v \
../../src/verilog/rtl/simf/build/fpu_pre_norm_div.v \
../../src/verilog/rtl/simf/build/fpu_pre_norm_mul.v \
../../src/verilog/rtl/simf/build/simf_alu.v \
../../src/verilog/rtl/simf/build/simf_instr_decoder.v \
../../src/verilog/rtl/simf/build/simf.v \
]
